import os

# set some options to use
cflags = '-O -c -O2 -Wextra -pedantic -std=c99'
# debug flags
debug = '-O -c -O0 -g'
# use the matern covariance function
usematern = ' -DMATERN'

env_prod = Environment(CCFLAGS = cflags+usematern)
env_debug = Environment(CCFLAGS = debug+usematern)

# source files to make the lib
src_files = Split('estimator.c emulator.c maximise.c maxbfgs.c bfgs.c')

libs=Split('gsl gslcblas m')

# make the libEmu library (shared)
env_prod.SharedLibrary('libEmu', src_files, LIBS=libs)

