import os
# a neater makefile

# pull in the libEmu file too and run it
SConscript(['libEmu/SConstruct'])
libs=Split('gsl gslcblas m pthread Emu')
libs2 = Split('gsl gslcblas m pthread')
cflags='-O2 -Wall -pg -g -pedantic -Wextra -std=gnu99 -I. -I.. -I./libEmu -I./multi'

env = Environment(CCFLAGS = cflags, CPPPATH=['./libEmu'], LIBPATH=['./libEmu'])
env.Append( LINKFLAGS = Split ('-z origin'))
env.Append( RPATH = env.Literal(os.path.join('\\$$ORIGIN', os.pardir, 'libEmu')))


# make the emulator program
main_src = Split('main.c ioread.c persist.c useful.c')
env.Program('emulator', main_src, LIBS=libs, LIBPATH=['./libEmu'])

# make the rbind lib
rbind_src = Split('rbind.c multi/multifit.c multi/multihelper.c useful.c')
env.SharedLibrary('libRbind', rbind_src, LIBS=libs, LIBPATH=['./libEmu'])
